[orangu-coordinator]
host = 127.0.0.1
port = 9000
startup_timeout = 180
# max_body_bytes = 67108864

[main]
role = all
llamacpp = llama-server -hf ggml-org/gemma-4-E4B-it-GGUF --host localhost --port 8100 --ctx-size 32768 -fa on --jinja

[explorer]
role = explorer
llamacpp = llama-server -hf unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF --host localhost --port 8200 --ctx-size 65536
